Feat/MET-5968 setting new data for target data
europeana/statistics-dashboard-backend pull request #26
Opened 2024-06-13 12:28 UTC by JoanaCMS

2024-06-24 13:50 UTC, jeortizquan requested changes
my suggestion to create a package and rename the dto's objects for the response, and also where it applies in other dto classes.

2024-06-25 09:45 UTC, JoanaCMS commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/internal/TargetType.java
> +    public String getValueAsString() {
Changed it to `getName`

2024-06-25 09:46 UTC, JoanaCMS commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/internal/HistoricalDataModel.java
Done!

2024-06-25 09:46 UTC, JoanaCMS commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/internal/TargetDataModel.java
Done!

2024-06-25 09:50 UTC, JoanaCMS commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/config/ApplicationConfiguration.java
> +
Removed!

2024-06-25 09:51 UTC, JoanaCMS commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryDataResult.java
I changed it, I created a new package called `dto`, I changed the names to what I thought made sense according to your suggestions

2024-06-26 12:32 UTC, jeortizquan reviewed
There is the initialization of targets that can be improved, when the worker starts.

2024-06-26 13:14 UTC, JoanaCMS commented on statistics-dashboard-worker/src/main/java/eu/europeana/statistics/dashboard/worker/execution/TargetDataRunner.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(AnalyzerRunner.class);
Fixed!

2024-06-27 08:04 UTC, jeortizquan approved these changes

2024-06-27 09:07 UTC, merged