MET-5968 Country Target Data (all)
europeana/statistics-dashboard-backend pull request #27
Opened 2024-06-28 08:47 UTC by andyjmaclean

2024-07-02 11:15 UTC, JoanaCMS requested changes

2024-07-03 07:41 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryTargetResult.java
> +
The front end does not expect the percentage from the back end.

2024-07-03 08:40 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +      ArrayList<CountryTargetResult> result = new ArrayList<>();
Done

2024-07-03 08:41 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/persistence/MongoSDTargetsDao.java
> +    ArrayList<Historical> queryResult = new ArrayList<>();
Done

2024-07-03 08:41 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/persistence/MongoSDTargetsDao.java
> +    ArrayList<Target> queryResult = new ArrayList<>();
Done

2024-07-03 09:19 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/HistoricalCountryTargetDataResult.java
> +    private int hq;
Done, but I've left it mapped to 'hq' in the JSON mapping.

2024-07-03 09:19 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/HistoricalCountryTargetDataResult.java
> +    private int three_d;
Done.

2024-07-03 09:39 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryTargetResult.java
> +    private boolean interim;
`interim` flags a target as being the interim target before the 2030 target.  It's used in the UI to decide whether or not the target line in the graph is drawn with a solid style or with a dashed style.  It's a derived field so I've removed it from the API.

2024-07-03 09:39 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryTargetResult.java
> +/**
Done

2024-07-03 09:40 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/HistoricalCountryTargetDataResult.java
> +    public int getThree_d() {
Done

2024-07-03 09:40 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/HistoricalCountryTargetDataResult.java
> +    public void setTHREE_D(Integer three_d) {
Done

2024-07-03 10:00 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    public List<HistoricalCountryTargetDataResult> getCountryDataAll(){
Done

2024-07-03 10:00 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    /**
Removed

2024-07-03 10:00 UTC, andyjmaclean commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/controller/CountryTargetDataController.java
> +
Done

2024-07-03 10:01 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    public String[] getTargetTypes(){
Removed

2024-07-03 10:16 UTC, andyjmaclean commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/controller/CountryTargetDataController.java
> +     *
I've refactored the class name "HistoricalCountryTargetData".

How much detail is needed in the Javadoc description from a simple getter?

2024-07-03 10:17 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    public List<Target> getCountryTargetsRaw(){
Deleted

2024-07-03 10:17 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    /**
Again, how much detail is required for a simple getter with a clear signature?

2024-07-03 11:12 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryTargetResult.java
> +    private String label;
It's been removed.

2024-07-03 11:13 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +        String label = Integer.toString(data.getYear());
Done

2024-07-03 12:30 UTC, andyjmaclean commented on statistics-dashboard-service/src/test/java/eu/europeana/statistics/dashboard/service/CountryTargetServiceTest.java
> +
Done

2024-07-03 12:30 UTC, andyjmaclean commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/config/ApplicationConfiguration.java
> +  public MongoSDTargetsDao getMongoSDTargetsDao(){
Done

2024-07-03 12:31 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +    private final MongoSDTargetsDao mongoSDTargetsDao;
Done

2024-07-04 09:21 UTC, andyjmaclean commented on statistics-dashboard-common/src/main/java/eu/europeana/statistics/dashboard/common/api/response/targetdata/CountryTargetResult.java
> +    private String targetType;
Done

2024-07-04 09:21 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +        int[] values = new int[]{ data.getThreeD(), data.getHighQuality(), data.getTotalRecords() };
Done

2024-07-04 09:21 UTC, andyjmaclean commented on statistics-dashboard-service/src/main/java/eu/europeana/statistics/dashboard/service/CountryTargetService.java
> +        for (int i = 0; i < values.length; i++) {
Removed

2024-07-04 10:56 UTC, JoanaCMS commented on statistics-dashboard-service/src/test/java/eu/europeana/statistics/dashboard/service/CountryTargetServiceTest.java
> +
Missing a test for the method ` getAllCountryData()`

2024-07-04 10:58 UTC, JoanaCMS commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/controller/CountryTargetDataController.java
> + */
Missing a test class for this class

2024-07-04 12:50 UTC, andyjmaclean commented on statistics-dashboard-rest/src/main/java/eu/europeana/statistics/dashboard/rest/config/ApplicationConfiguration.java
> +  public CountryTargetService getCountryTargetService(MongoSDTargetsDao mongoSDTargetsDao){
Done

2024-07-05 09:02 UTC, merged